# 
# Set SauceLabs options to be used.
#
# ( Only used by lib/module/sauce, ignored otherwise. )
#
---
:username: 'your-username'
:api_key:  'your-api-key'
:platforms:                         # Which versions of Windows & OS X to use.
  :windows: '8'
  :os_x: '10.8'
:browsers:                          # The latest versions of each supported browser.
  :chrome: '31'
  :internet_explorer: '10'
  :firefox: '25'
  :safari: '6'
