$:<< File.join(File.dirname(__FILE__),'..')

# Require regression testing code.
require 'lib/ole-regress.rb'

# Require shared contexts.
require 'spec/shared.rb'
Dir['spec/*/shared.rb'].sort.each {|file| require file}

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Initiate a new OLE QA Framework Session before each spec.
  config.before(:all) do
    opts = OLE_QA::RegressionTest::Options
    @ole = OLE_QA::Framework::Session.new(opts)
  end

  config.after(:all) do
    @ole.quit
  end
end
